num-threads: 1
temp-buffer-path: /tmp/h2o
proxy.emit-x-forwarded-headers: ON
proxy.timeout.keepalive: 15000

listen:
  - host: 127.0.0.1
    port: 80

hosts:
  "health.invalid":
    paths:
      /h2o-health:
        file.dir: /usr/share/h2o/health
      /pingora-health:
        file.dir: /usr/share/h2o/health

  "app.test":
    paths:
      /:
        proxy.reverse.url: http://127.0.0.1:9
